### ISSUE TITLE
Améliorations responsive design 

### ISSUE THREAD

**Issue by bastou2316** [HE-Arc/RebelLegion#10]
- [x] Couleur de la police (gris clair sur fond or) à modifier car difficilement lisible
- [x] Réduire la taille du fond rouge dans le menu pour ne pas déborder sur la croix de fermeture
- [x] Lorsque la fenêtre est réduite, une partie du texte de la page d'accueil disparaît

**Comment by matbandeli** [comment]
- [x] Contenu de la page d'accueil (1ère partie de type carrousel) mieux agencé pour de grand écrans
